---
#
# Ansible managed
#
repository:
  description: Install and configure Etherpad on your system.
  homepage: https://buluma.co.ke/
  topics: etherpad, ansible, molecule, tox, playbook, hacktoberfest
