---
#
# Ansible managed
#
repository:
  description: Install and configure Etherpad on your system.
  homepage: https://buluma.github.io/
  topics: etherpad, ansible, molecule, tox, playbook, hacktoberfest
